on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - run: sudo apt install -y libpcap-dev  
      - uses: mlugg/setup-zig@v2
      - uses: actions/checkout@v4
      - run: zig build
